### ISSUE TITLE
Allow channel slug customization in the Apps dashboard UI

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/dummy-payment-app#31]
- I dont have "default-channel" in my instance
- All queries and mutations assume it's existence:

<img width="1240" alt="image" src="https://github.com/user-attachments/assets/464c6093-06cb-4e59-983d-a237d221c642">

Probable solution:
Add field for specifying the channel. If pulling list of the channels from API is not viable, plain text field will be a next-best-solution.

**Comment by witoszekdev** [comment]
Thanks for feedback, I've added a combobox to select channel before you create the checkout 🙌🏻 

![1_checkout](https://github.com/user-attachments/assets/b376148d-27ad-4b63-ab30-398123737ea8)
